### ISSUE TITLE
Deal with experimental VM options warnings in 23.1/24.0

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#184]
With Mandrel 23.1 and/or GraalVM 24.0 almost all `-H` options get flagged like so:

```
org.opentest4j.AssertionFailedError: 
build-and-run.log log should not contain error or warning lines that are not whitelisted. See /disk/graal/upstream-sources/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.DebugSymbolsTest/debugSymbolsSmokeGDB/build-and-run.log and check these offending lines: 
Warning: The option '-H:+PreserveFramePointer' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:-DeleteLocalSymbols' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:+TrackNodeSourcePosition' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:GenerateDebugInfo=1' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:+OmitInlinedMethodDebugLineInfo' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: The option '-H:+DebugCodeInfoUseSourceMappings' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue. ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.DebugSymbolsTest.debugSymbolsSmokeGDB(DebugSymbolsTest.java:190)
```

We need to add hooks in the test suite so as to surround them by `-H:+UnlockExperimentalVMOptions` and `-H:-UnlockExperimentalVMOptions`.

**Comment by zakkak** [comment]
> The above are probably a bad example as they're added by Quarkus.

For reference the Quarkus PR for handling this is https://github.com/quarkusio/quarkus/pull/35379

**Comment by jerboaa** [comment]
> > The above are probably a bad example as they're added by Quarkus.
> 
> For reference the Quarkus PR for handling this is [quarkusio/quarkus#35379](https://github.com/quarkusio/quarkus/pull/35379)

Doesn't seem the full story. See https://github.com/quarkusio/quarkus/issues/35788

**Comment by zakkak** [comment]
> Doesn't seem the full story. See [quarkusio/quarkus#35788](https://github.com/quarkusio/quarkus/issues/35788)

Good catch. I created a complementary PR for the rest of the options https://github.com/quarkusio/quarkus/pull/35772

**Comment by jerboaa** [comment]
I'm splitting all those failures out into individual issues so we can have a more accurate historical view.

**Comment by jerboaa** [comment]
Closing this one as I think all experimental VM options are now either ignored or properly dealt with. See https://github.com/Karm/mandrel-integration-tests/issues/184#issuecomment-1710109728 for all individual issues that got fixed.
