### ISSUE TITLE
[23.1] quarkusFullMicroProfile test fails due to experimental VM options warning

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#190]
It fails with:

```
quarkusFullMicroProfile{TestInfo}  Time elapsed: 112.276 s  <<< FAILURE!
org.opentest4j.AssertionFailedError:
build-and-run.log log should not contain error or warning lines that are not whitelisted. See /disk/graal/upstream-sources/mandrel-integration-tests/testsuite/target/archived-logs/org.graalvm.tests.integration.RuntimesSmokeTest/quarkusFullMicroProfile/build-and-run.log and check these offending lines:
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/netty-transport/reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue.
Warning: The option '-H:Log=registerResource:' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future. ==> expected: <true> but was: <false>
        at org.graalvm.tests.integration.RuntimesSmokeTest.testRuntime(RuntimesSmokeTest.java:166)
        at org.graalvm.tests.integration.RuntimesSmokeTest.quarkusFullMicroProfile(RuntimesSmokeTest.java:194)
```

**Comment by zakkak** [comment]
The `-H:ReflectionConfigurationResources` part [comes from netty](https://github.com/netty/netty/blob/f1fa227ddf675f055766d04900cce6804fd7f710/transport/src/main/resources/META-INF/native-image/io.netty/netty-transport/native-image.properties#L15)

`-H:Log=registerResource:` comes from [mandre](https://github.com/Karm/mandrel-integration-tests/blob/88a7a8f1afa65be266f37409159df4036b511132/testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java#L55)

@Karm is the Log part necessary for the test? If so, we need a way to wrap it with `-H:+-UnlockExperimentalVMOptions` when using GraalVM >=23.1

**Comment by zakkak** [comment]
Upstream PR for netty 4: https://github.com/netty/netty/pull/13596

**Comment by jerboaa** [comment]
The remaining issue is down to netty native-image config, tracked elsewhere.

See:
https://github.com/graalvm/mandrel/actions/runs/6159630722/job/16716434614#step:11:10310

Can we allow-list those log lines to reduce noise?

**Comment by zakkak** [comment]
> Can we allow-list those log lines to reduce noise?

+1 from me
