### ISSUE TITLE
Integration test for Graal VM sdk's Version API

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#20]
We have a smoke test for the `Version` API in [GraalVM20OrLater.java](https://github.com/Karm/mandrel-integration-tests/blob/master/apps/versions/src/main/java/version/GraalVM20OrLater.java#L33), but this only verifies no IllegalArgumentException is being thrown. It does not verify if it actually returns the correct result. For example, if run with a Mandrel `21.1.0-dev` build, does it actually report the correct version, `21.1.0-dev` or something else? We need a test for this, which perhaps downloads a fixed build for which we know the version, and then asserts the correct version is reported via the API.

See https://github.com/graalvm/mandrel-packaging/pull/112#issuecomment-809235585 which prompted me to create this issue.

**Comment by jerboaa** [comment]
@Karm FYI. We should have a test for this before 21.1.0 gets released.

**Comment by Karm** [comment]
We use the Version in the TS now.
