### ISSUE TITLE
M 23.1 JDK 21 Q 3.x Warnings

### ISSUE THREAD

**Issue by Karm** [Karm/mandrel-integration-tests#219]
```
build-and-run.log log should not contain error or warning lines that are not whitelisted. See /home/tester/jenkins/workspace/mandrel-linux-container-integration-tests/96a0edf0/testsuite/target/archived-logs/org.graalvm.tests.integration.RuntimesSmokeTest/quarkusEncodingIssues/build-and-run.log and check these offending lines: 
Warning: The option '-H:ReflectionConfigurationResources=META-INF/native-image/io.netty/netty-transport/reflection-config.json' is experimental and must be enabled via '-H:+UnlockExperimentalVMOptions' in the future.
Warning: Please re-evaluate whether any experimental option is required, and either remove or unlock it. The build output lists all active experimental options, including where they come from and possible alternatives. If you think an experimental option should be considered as stable, please file an issue. ==> expected: <true> but was: <false>
```

Eventually whitelist...

**Comment by zakkak** [comment]
There is an [upstream netty PR](https://github.com/netty/netty/pull/13596) that should fix this. In the meantime I agree that we should whitelist it.

**Comment by jerboaa** [comment]
@Karm Why is #203 not sufficient?

**Comment by Karm** [comment]
> @Karm Why is #203 not sufficient?

On my Cosmo Communicator ™ now, might not have the full context pulled, but I think the whitelist was not complete, did not include container tests for other Q apps.

**Comment by jerboaa** [comment]
It would be good if steps to reproduce would be provided for issues being opened in the future :)

**Comment by Karm** [comment]
Whitelisted. Closing. https://github.com/Karm/mandrel-integration-tests/blob/master/testsuite/src/it/java/org/graalvm/tests/integration/utils/WhitelistLogLines.java#L121
