### ISSUE TITLE
Adapt quarkus-full-microprofile based tests to work with Quarkus >= 3.6.0

### ISSUE THREAD

**Issue by zakkak** [Karm/mandrel-integration-tests#225]
Starting with Quarkus 3.6.0 `quarkus-smallrye-opentracing` is no longer a core extension. `quarkus-full-microprofile` depends on it and thus fails with Quarkus >= 3.6.0 (as observed in https://github.com/Karm/mandrel-integration-tests/issues/223)

https://github.com/Karm/mandrel-integration-tests/pull/224 disabled quarkus-full-microprofile based tests for Quarkus >= 3.6.0, which comes with the big drawback that we are no longer running 3 important tests.

@jerboaa suggested in https://github.com/Karm/mandrel-integration-tests/issues/223#issuecomment-1820603355:

> how about we produce a profile that activates based on the quarkus version and adds the quarkiverse dependency for later versions?

**Comment by Karm** [comment]
I will create a patch. This is IMHO connected to MicroProfile specification that is getting rid of a one monitoring API in favor of another, i.e. we get rid of Jaeger things in favor of OpenTelemetry  for good. 

We will need .patch so as older Qurkus versions keep working and we can have the same app.  Given the simplicity of the app, I think it's still more manageable than having a separate test app in apps dir.
