### ISSUE TITLE
Switching Vert.x app to RestEasy Reactive, fails debugging session

### ISSUE THREAD

**Issue by Karm** [Karm/mandrel-integration-tests#229]
I have a patch that ports the Vert.x test app to contemporary Quarkus 3.x suggested API, RestEasy Reactive.

[quarkus_3.x.reactive.patch.txt](https://github.com/Karm/mandrel-integration-tests/files/13486026/quarkus_3.x.reactive.patch.txt)

It fails debugging session:

"Cannot execute this command while the selected thread is running"

```
[ERROR] Failures: 
[ERROR]   DebugSymbolsTest.debugSymbolsQuarkusContainer:396->carryOutGDBSession:501 There were errors in the GDB session. Note that commands in the session might depend on each other. Errors: 
Command 'bt' did not match the expected pattern in time '.*at org/acme/vertx/Fruit.java:48.*'.
Output was:
"bt
""Selected thread is running.
"^error,msg="Selected thread is running."(gdb) , 
Command 'list' did not match the expected pattern in time '.*48.*return client.query\("SELECT id, name FROM fruits ORDER BY name ASC.*'.
Output was:
"list
""1     org/graalvm/compiler/replacements/BoxingSnippets.java: No such file or directory.
"^done(gdb) , 
Command 'c&' did not match the expected pattern in time '.*Continuing.*'.
Output was:
"c&
""Cannot execute this command while the selected thread is running.
"^error,msg="Cannot execute this command while the selected thread is running."(gdb)  ==> expected: <true> but was: <false>
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

**Comment by Karm** [comment]
Hello, @zakkak, I will use our version support in GDBSession class to create a compatible debug flow, but I wonder what would be expected here. Do I list threads and select the one that hit the breakpoint or can I tell that to gdb to do it automatically? :( 

https://sourceware.org/gdb/current/onlinedocs/gdb.html/All_002dStop-Mode.html

**Comment by zakkak** [comment]
@Karm I am not sure I get what the issue is.

My understanding of the error you are seeing is that another comment failed earlier. We should only issue `bt` after we expect the app to hit a breakpoint.

If you set a breakpoint and it's reached gdb automatically selects the thread that hit the breakpoing if I am not mistaken so there is nothing special to do.

**Comment by jerboaa** [comment]
@Karm You can use `commands` gdb command to run something based on a set breakpoint number. See: https://sourceware.org/gdb/current/onlinedocs/gdb.html/Break-Commands.html
