### ISSUE TITLE
Maybe add new JFR log lines to whitelist

### ISSUE THREAD

**Issue by roberttoyonaga** [Karm/mandrel-integration-tests#237]
### Summary
Adding this so it can be tracked and I don't forget about it. 
Depending on the outcome of https://github.com/oracle/graal/pull/8037,  new lines may need to be whitelisted for JFR.

```
[warn][jfr,setting] @Deprecated JFR events, and leak profiling are not yet supported.
[warn][jfr,setting] Exception occurred when setting value "forRemoval" for class jdk.jfr.internal.Control
Passed
```

**Comment by jerboaa** [comment]
Thanks for the report @roberttoyonaga. Could you please prioritize getting those added? Thanks! We see it in CI now:
https://github.com/Karm/mandrel-integration-tests/issues/208#issuecomment-1859938636

**Comment by roberttoyonaga** [comment]
> Thanks for the report @roberttoyonaga. Could you please prioritize getting those added? Thanks! We see it in CI now: [#208 (comment)](https://github.com/Karm/mandrel-integration-tests/issues/208#issuecomment-1859938636)

Yes, will do

**Comment by jerboaa** [comment]
> We see it in CI now: [#208 (comment)](https://github.com/Karm/mandrel-integration-tests/issues/208#issuecomment-1859938636)

The issue we see in CI is #239 (related, but not quite the issue this is tracking). We may have to update once https://github.com/oracle/graal/pull/8037 merges upstream and close this issue.

**Comment by roberttoyonaga** [comment]
Closing now because it's been resolved by https://github.com/Karm/mandrel-integration-tests/pull/242
