### ISSUE TITLE
org.graalvm.tests.integration.JFRTest.jfrPerfTest fails with latest quarkus main

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#250]
The JFR perf runner seems to no longer compile with quarkus main:

```
 Error:  Failed to execute goal on project jfr-native-image-performance: Could not resolve dependencies for project org.graalvm.tests.integration:jfr-native-image-performance:jar:1.0.0-SNAPSHOT: Could not find artifact io.quarkus:quarkus-resteasy-reactive:jar:999-SNAPSHOT -> [Help 1]
```

See:
https://github.com/graalvm/mandrel/actions/runs/8289954741/job/22688018133#step:11:13726

I believe there was a change in quarkus main which caused this. If we knew the fix, we could apply a similar one.

/cc @Karm

**Comment by jerboaa** [comment]
Seems to affect 24.0 too (JDK 22):
https://github.com/graalvm/mandrel/actions/runs/8289954741/job/22688076873#step:11:13736

**Comment by jerboaa** [comment]
We see this failure everywhere now. Please prioritize a fix. Thanks!

**Comment by Karm** [comment]
@jerboaa Ack.

**Comment by Karm** [comment]
The binary is not there, because the Q build fails:

Mandrel: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21
Quarkus: 9d6f6335c66

```
[WARNING] ClassRealm[plugin>io.quarkus:quarkus-maven-plugin:999-SNAPSHOT, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@277050dc]
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for io.quarkus.maven.QuarkusBootstrapProvider annotated with interface org.eclipse.sisu.inject.TypeArguments$Implicit was bound.
  Did you mean?
    io.quarkus.maven.QuarkusBootstrapProvider bound  at org.eclipse.sisu.wire.LocatorWiring

  at org.eclipse.sisu.wire.LocatorWiring

1 error
```

Gonna port the app/see how it goes...
