### ISSUE TITLE
JDK 24+13 based Mandrel 24.2 builds produce warnings

### ISSUE THREAD

**Issue by jerboaa** [Karm/mandrel-integration-tests#278]
After https://github.com/oracle/graal/pull/9621, mandrel builds produce warnings due to some GraalVM enterprise modules which aren't there for mandrel. Example warning:

```
WARNING: Unknown module: com.oracle.svm.svm_enterprise specified to --enable-native-access
WARNING: Unknown module: com.oracle.graal.graal_enterprise specified to --enable-native-access
```

Seen in CI here:
https://github.com/graalvm/mandrel/actions/runs/10747037745/job/29809505730#step:11:12828

We'd need a patch in upstream GraalVM so as to not add those modules for Mandrel. Example patch:
https://github.com/jerboaa/graal/commit/74a2e81efb6c71367a41ee6e864d8ac3c4d4e416

**Comment by jerboaa** [comment]
Discussion about this here:
https://github.com/oracle/graal/pull/9621#discussion_r1745904042

**Comment by jerboaa** [comment]
This should be fixed once https://github.com/oracle/graal/pull/9654 merges.

**Comment by zakkak** [comment]
https://github.com/oracle/graal/pull/9654 is now merged but there are still related warnings showing up in some cases, e.g.:

```
WARNING: A restricted method in java.lang.System has been called
WARNING: Restricted methods will be blocked in a future release unless native access is enabled
WARNING: java.lang.System::loadLibrary has been called by com.aayushatharva.brotli4j.Brotli4jLoader in an unnamed module (file:/D:/a/mandrel/mandrel/apps/quarkus-full-microprofile/target/quarkus-native-image-source-jar/lib/com.aayushatharva.brotli4j.brotli4j-1.16.0.jar)
WARNING: Use --enable-native-access=ALL-UNNAMED to avoid a warning for callers in this module ==> expected: <true> but was: <false>
	at org.graalvm.tests.integration.RuntimesSmokeTest.testRuntime(RuntimesSmokeTest.java:156)
	at org.graalvm.tests.integration.RuntimesSmokeTest.quarkusFullMicroProfile(RuntimesSmokeTest.java:200)
```

See https://github.com/graalvm/mandrel/actions/runs/10985696189/job/30498692042

**Comment by zakkak** [comment]
> The alternative is to allow-list those log lines. Example happening at image build time here:
> 
> https://github.com/graalvm/mandrel/actions/runs/10985696189/job/30498692042#step:10:8773

The warning [shows up in Quarkus integration tests as well](https://github.com/graalvm/mandrel/actions/runs/10985696189/job/30498538862#step:12:449) so I believe this is something to be handled in Quarkus.

**Comment by jerboaa** [comment]
> > The alternative is to allow-list those log lines. Example happening at image build time here:
> > https://github.com/graalvm/mandrel/actions/runs/10985696189/job/30498692042#step:10:8773
> 
> The warning [shows up in Quarkus integration tests as well](https://github.com/graalvm/mandrel/actions/runs/10985696189/job/30498538862#step:12:449) so I believe this is something to be handled in Quarkus.

It would be great if Quarkus could move to automatic modules.

**Comment by jerboaa** [comment]
I'm closing this as it was originally about svm modules that produced warnings, which is gone. The brotli issue is tracked in: https://github.com/Karm/mandrel-integration-tests/issues/284
