### ISSUE TITLE
debugSymbolsQuarkusContainer: Error: OCI runtime error: cannot set memory swappiness with cgroupv2

### ISSUE THREAD

**Issue by Karm** [Karm/mandrel-integration-tests#56]
Latest podman, maybe OS issues? TODO: try on latest Fedora

**Comment by jerboaa** [comment]
@Karm I'm intrigued. How would I reproduce this?

**Comment by jerboaa** [comment]
Is anything in this test setting `--memory-swappiness`? From the man page of podman run:
```
   --memory-swappiness=number
       Tune a container's memory swappiness behavior. Accepts an integer between 0 and 100.

       This flag is not supported on cgroups V2 systems.
```

**Comment by Karm** [comment]
@jerboaa  It is caused by this line: https://github.com/Karm/mandrel-integration-tests/blob/master/testsuite/src/it/java/org/graalvm/tests/integration/utils/BuildAndRunCmds.java#L66

Test case: 
- launch Q app in a container
- launch gdb in a container
- carry out gdb session inside the container

Is it really necessary to have it set to 0 for the session to work?   I don't recall. Will try presently....

**Comment by jerboaa** [comment]
OK, this won't work on a cgroups v2 system. So I suggest to figure out why you need this swappiness setting in the first place and find out what the alternatives are to achieve the same (or similar) result. Perhaps setting `--memory=X` and `--memory-swap=X` would help to disable swap.
