### ISSUE TITLE
Docker on Windows and Linux, Podman on Linux: time to first request and memory consumption

### ISSUE THREAD

**Issue by Karm** [Karm/mandrel-integration-tests#6]
```
linux.time.to.first.ok.request.threshold.ms=1500
linux.RSS.threshold.kB=21504
windows.time.to.first.ok.request.threshold.ms=700
windows.RSS.threshold.kB=7800
```

Looks like Linux is more greedy than Windows. In fact, this is caused by a discrepancy in Docker vs. Podman runtimes.

## Docker, Linux
`docker run -i --rm -p 8080:8080 --name my-quarkus-mandrel-app-container my-quarkus-mandrel-app`
Measurements:
|App|buildTimeMs|timeToFirstOKRequestMs|RSSKb|
| --- | --- | --- | --- |
|QUARKUS_BUILDER_IMAGE_ENCODING|103770|1178|7168|

## Docker, Windows
(running Linux container)

`cmd /C docker run -i --rm -p 8080:8080 --name my-quarkus-mandrel-app-container my-quarkus-mandrel-app`
Measurements:
|App|buildTimeMs|timeToFirstOKRequestMs|RSSKb|
| --- | --- | --- | --- |
|QUARKUS_BUILDER_IMAGE_ENCODING|391558|1048|5120|

## Podman, Linux
`podman run -i --rm -p 8080:8080 --name my-quarkus-mandrel-app-container my-quarkus-mandrel-app`
Measurements:
|App|buildTimeMs|timeToFirstOKRequestMs|RSSKb|
| --- | --- | --- | --- |
|QUARKUS_BUILDER_IMAGE_ENCODING|104057|568|19456|

# TODO

We need to add container runtime in the thresholds properties to distinguish between podman and docker.

**Comment by Karm** [comment]
@zakkak  Fun trivia :)

**Comment by zakkak** [comment]
Wow, looks like something podman people would be interested in!

**Comment by Karm** [comment]
Dated,
