### ISSUE TITLE
Why do you use Quarkus with Graalvm

### ISSUE THREAD

**Issue by HelloTo4x** [Karm/mandrel-integration-tests#98]
Hi, why do you use Quarkus instead of Spring Native, i see Spring Native has large ecosystem with Spring, so we can do it. Can u tell me if you about your purpose when using Quarkus, the pros and cons of Quarkus, thank u so much

**Comment by zakkak** [comment]
Closing as off topic. You may use https://github.com/quarkusio/quarkus/discussions/ or https://quarkusio.zulipchat.com for such topics.
